name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  responsive_builder:  ^0.7.1  # Specify a version
  entry: ^1.0.0  # Add a version; adjust based on your needs
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/  # Directory
    # Add specific files if needed, e.g.:
    # - assets/Images/image1.png
    # - assets/Images/image2.png

  fonts:
    - family: HindSiliguri
      fonts:
        - asset: Fonts/HindSiliguri-Bold.ttf
        - asset: Fonts/HindSiliguri-Light.ttf
        - asset: Fonts/HindSiliguri-Medium.ttf
        - asset: Fonts/HindSiliguri-Regular.ttf
        - asset: Fonts/HindSiliguri-SemiBold.ttf